### ISSUE TITLE
Compatibility with Magento 2.3.1

### ISSUE THREAD

**Issue by cstergianos** [SpotlerSoftware/magento2-mailplus-connector#11]
Hello,

The last magento upgrade was just released but unfortunately the extension is currently not compatible with it. Are you already working on a fix?

**Comment by evs-xsarus** [comment]
Also, the module is incompatible with PHP 7.2.x, I get this error on Magento 2.3.1 when requiring the module:

```
  [InvalidArgumentException]                                                                                         
  Package mailplus/mailplus-connector at version  has a PHP requirement incompatible with your PHP version (7.2.16) 
```

**Comment by fvschie** [comment]
We've updated the project to support both Magento 2.3.1 and PHP 7.2.x. Please check out v1.4.7
