### ISSUE TITLE
Add support for PHP 7.4

### ISSUE THREAD

**Issue by marcoboom** [SpotlerSoftware/magento2-mailplus-connector#19]
Please update the composer.json to support php 7.4

**Comment by Tantuss** [comment]
As there is 0 response from the builders of this extension, probably the only solution is to fork it and change it yourself.

**Comment by evs-xsarus** [comment]
When doing this, please add support for PHP 8.x

**Comment by gjportegies** [comment]
Please update this module to support PHP 7.4. As of Magento version 2.4 it is recommended to use PHP 7.4. In upcoming version Magento 2.3.7 will support PHP 7.4 as well. There is already a pull request fixing this issue.

**Comment by leonhelmus** [comment]
Please merge the pull request.

**Comment by JKingma** [comment]
Can this or be merged, please?

**Comment by nielsnoorlander** [comment]
We'll be adding PHP 7.4 & 8.0 support as soon possible.

**Comment by 808brinks** [comment]
A fix for this has been merged: https://github.com/SpotlerSoftware/magento2-mailplus-connector/pull/23
