### ISSUE TITLE
magento 2.2.0 compatibility

### ISSUE THREAD

**Issue by vincenthornikx** [SpotlerSoftware/magento2-mailplus-connector#2]
Could you indicate when this module will be updated to be compatible with Magento 2.2.0?

Regards,
Vincent

**Comment by PaulBoss** [comment]
We have an internal ticket open for Magento 2.2.0 compatibility. We do not have a fixed date set but this should be release within the next couple of weeks.

**Comment by PaulBoss** [comment]
Version 1.4.0 has de fixes for Magento 2.2.X compatibility
