### ISSUE TITLE
setup:upgrade fails because of empty acl.xml file

### ISSUE THREAD

**Issue by acohin** [SpotlerSoftware/magento2-mailplus-connector#6]
Magento fails to complete setup:upgrade with the following error:
```
Running schema recurring...Invalid XML in file ..../vendor/mailplus/mailplus-connector/etc/acl.xml:
Element 'acl': Missing child element(s). Expected is ( resources ).
Line: 4
```
This is because Magento 2.2+ enforces the xml schema and expects one or more acl rules to be declared, while the acl.xml file is empty. This occurs for me in an installation I just upgraded from 2.1, I'm not entirely clear on why it doesn't occur on a fresh Magento 2.2 installation. It's probably turned off for new installations.

Removing the acl.xml file since it's doesn't do anything anyway fixes the issue.

Or define ACLs :-)

Update: after some plodding around I've found that the error doesn't occur in a fresh installation because M2 then runs in default deployment mode. M2 validates the xml schema only when running in developer mode.

**Comment by PaulBoss** [comment]
This has been fixed. #7  has been merged in v1.4.2.
