### ISSUE TITLE
Add package to packagist

### ISSUE THREAD

**Issue by marcelmediact** [SpotlerSoftware/magento2-mailplus-connector#8]
Could you please add this package to https://packagist.org/ ?
This would make the installation process a lot faster than through VCS.

**Comment by PaulBoss** [comment]
Could you please explain how this will be a lot faster? There should be almost no difference in using packagist or using an extra repo to get a package via composer (e.g. one command extra for adding the github repo which results in a few lines added to the composer.json)

**Comment by riotrick** [comment]
Managing repositories is a bit cumbersome as well as being slower.

But o.t.o.h. what's against adding it to packagist? It's nothing more than creating an account and submitting the github url. It'll auto-update when you push new versions to github.

**Comment by vpodorozh** [comment]
It would be nice if the package will be available in packagist, it will simplify package installation and update via composer.

**Comment by ArjenMiedema** [comment]
Any news on this? I'd really like to have this added to Packagist, as it makes it a lot more maintainable with several projects using a lot of different packages via VCS.

**Comment by chefbuitenhuis** [comment]
I'd like to bump this for the above-mentioned reasons. Please add it to Packagist.

**Comment by LexKoomen** [comment]
Can you guys give an update on this issue? It's been a year now and we would all love this to be added to packagist.

**Comment by ArjenMiedema** [comment]
Since there's no reply on this issue for over a year now and I really want this to be available, I just added it to my company's Packagist account (MediaCT). You can find it here from now on: https://packagist.org/packages/mailplus/mailplus-connector.

**Comment by JKetelaar** [comment]
Still waiting for this...

**Comment by JKetelaar** [comment]
It's a solution... But I would rather prefer them to maintain and update it

**Comment by ArjenMiedema** [comment]
I totally agree, but since they haven't responded to this for over a year now, I don't expect them to take action anytime soon. So until then, I'll ensure it will be up-to-date

**Comment by JKetelaar** [comment]
Thanks @ArjenMiedema for your solution, it definitely isn't ideal. This is the same for PR #14, as they still haven't solved that one.

If this isn't working out properly, I will be moving to another product instead that keeps their software up-to-date.

**Comment by PaulBoss** [comment]
We cannot add the package to packagist since the package is already there

![Screenshot from 2020-01-22 12-07-28](https://user-images.githubusercontent.com/5463398/72889412-ebe9e700-3d0f-11ea-999c-371af8c621b8.png)

@ArjenMiedema could you give me admin acces to that or could you remove the package so we can re-add it?

**Comment by ArjenMiedema** [comment]
@PaulBoss I gave you access to the package, so you should be able to link it.

**Comment by PaulBoss** [comment]
I've linked the package and the hook is active. The latest release is also visible on packagist now.
